// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8nA8UWPlfp0CoOeZ8J3JCTVBjrsv38rM',
    appId: '1:744764027267:android:950fb921ed22eed5b006b6',
    messagingSenderId: '744764027267',
    projectId: 'cris-app-eed26',
    storageBucket: 'cris-app-eed26.appspot.com',
    androidClientId: '744764027267-up6t6f1439fulcl9pt8nkg8m8icaq4b1.apps.googleusercontent.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDS_pI_M_ve5DZ9hepkWW5pwo5eyWx4KDs',
    appId: '1:744764027267:ios:a9adb6b9d7419e80b006b6',
    messagingSenderId: '744764027267',
    projectId: 'cris-app-eed26',
    storageBucket: 'cris-app-eed26.appspot.com',
    androidClientId: '744764027267-up6t6f1439fulcl9pt8nkg8m8icaq4b1.apps.googleusercontent.com',
    iosClientId: '744764027267-te6m9qlr0m58mm4ovd9jltdifoqeb1qn.apps.googleusercontent.com',
    iosBundleId: 'com.example.crisApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5dGZGcR51NgFW1E2Um0TK5zqz0BYxz4U',
    appId: '1:744764027267:web:8af5392976d81ec2b006b6',
    messagingSenderId: '744764027267',
    projectId: 'cris-app-eed26',
    authDomain: 'cris-app-eed26.firebaseapp.com',
    storageBucket: 'cris-app-eed26.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5dGZGcR51NgFW1E2Um0TK5zqz0BYxz4U',
    appId: '1:744764027267:web:8af5392976d81ec2b006b6',
    messagingSenderId: '744764027267',
    projectId: 'cris-app-eed26',
    authDomain: 'cris-app-eed26.firebaseapp.com',
    storageBucket: 'cris-app-eed26.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS_pI_M_ve5DZ9hepkWW5pwo5eyWx4KDs',
    appId: '1:744764027267:ios:a9adb6b9d7419e80b006b6',
    messagingSenderId: '744764027267',
    projectId: 'cris-app-eed26',
    storageBucket: 'cris-app-eed26.appspot.com',
    androidClientId: '744764027267-up6t6f1439fulcl9pt8nkg8m8icaq4b1.apps.googleusercontent.com',
    iosClientId: '744764027267-te6m9qlr0m58mm4ovd9jltdifoqeb1qn.apps.googleusercontent.com',
    iosBundleId: 'com.example.crisApp',
  );

}